name: Deploy to Docker Desktop Kubernetes

on:
  push:
    branches:
      - master  # your branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f k8s/journal/frontend/
