name: Test Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print info from runner
        run: |
          echo "Hello from self-hosted runner!"
          echo "Hostname: $(hostname)"
          whoami
